stages:
  - test
  - integration
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: python:3.11-slim
  before_script:
    - python -V
    - pip install --upgrade pip
    - pip install -r api/requirements.txt || true
    - pip install pytest pydantic requests
  script:
    - pytest
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - junit.xml

integration:
  stage: integration
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    OLLAMA_LLM: "llama3.1:8b"
    OLLAMA_EMBED: "nomic-embed-text"
  before_script:
    - apk add --no-cache bash docker-cli-compose curl jq
    - docker compose version
  script:
    - |
      set -euo pipefail
      docker compose -f docker-compose.yml up -d qdrant ollama-prepull
      # wait for pre-pull to finish; don't fail pipeline if it exits non-zero
      PREP=$(docker ps -q --filter name=ollama-prepull || true)
      if [ -n "$PREP" ]; then docker wait "$PREP" || true; fi
      docker compose -f docker-compose.yml up -d ollama
      # run just the import smoke test locally (no HTTP)
      docker run --rm -v "$CI_PROJECT_DIR:/work" -w /work --network host python:3.11-slim \
        bash -lc "pip install -r api/requirements.txt || true && pip install pytest && pytest tests/integration"
  after_script:
    - docker compose -f docker-compose.yml down -v
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == "main"

build-image:
  stage: build
  image: quay.io/podman/stable:latest
  tags: ["test-runner"]
  variables:
    STORAGE_DRIVER: vfs
  before_script:
    - podman login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  script:
    - podman build --storage-driver vfs -t "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA" ./api
    - podman push "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA"
  
build-image:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  tags: ["test-runner"]
  variables:
    DOCKER_CONFIG: /kaniko/.docker
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "gitlab-ci-token" "$CI_JOB_TOKEN" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    
    # Debug network
    - echo "Registry: $CI_REGISTRY"
    - nslookup "$CI_REGISTRY" || true
    
  script:
    - /kaniko/executor
      --context ./api
      --dockerfile ./api/Dockerfile
      --destination "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA"
      --cache=true
      --insecure-registry="$CI_REGISTRY"
      --skip-tls-verify-registry="$CI_REGISTRY"
      --verbosity=debug

