services:
  # 1) Register local Zephyr model inside Ollama (reads your Modelfile)
  model-create:
    image: ollama/ollama:0.3.14
    env_file: .env
    entrypoint: ["sh","-lc"]
    command: >
      ollama serve & sleep 2;
      ollama create ${CUSTOM_MODEL_TAG} -f ${CUSTOM_MODEL_DIR_IN_CONTAINER}/Modelfile;
      kill %1 || true
    environment:
      - OLLAMA_MODELS=/root/.ollama
      - OLLAMA_NO_GPU=1
    volumes:
      - ollama_models:/root/.ollama
      - ./models:/models:ro
    restart: "no"

  # 2) (Optional) Pre-pull embedding model from registry
  #    If your cluster has no internet, comment this out
  ollama-prepull-embed:
    image: ollama/ollama:0.3.14
    env_file: .env
    depends_on:
      model-create:
        condition: service_completed_successfully
    entrypoint: ["sh","-lc"]
    command: >
      ollama serve & sleep 2;
      ollama pull ${OLLAMA_EMBED} || true;
      kill %1 || true
    environment:
      - OLLAMA_MODELS=/root/.ollama
      - OLLAMA_NO_GPU=1
    volumes:
      - ollama_models:/root/.ollama
    restart: "no"

  # 3) Long-running Ollama server
  ollama:
    image: ollama/ollama:0.3.14
    depends_on:
      model-create:
        condition: service_completed_successfully
      ollama-prepull-embed:
        condition: service_completed_successfully
    environment:
      - OLLAMA_MODELS=/root/.ollama
      - OLLAMA_NO_GPU=1
    volumes:
      - ollama_models:/root/.ollama
      - ./models:/models:ro
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:11434/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60

  # 4) Qdrant vector DB
  qdrant:
    image: qdrant/qdrant:v1.11.0
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:6333/readyz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  # 5) FastAPI service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: local/rag-api:0.1.0
    restart: unless-stopped
    env_file: .env
    depends_on:
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_healthy
    ports:
      - "8080:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health/live >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  ollama_models:
  qdrant_storage: