services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    restart: unless-stopped
    ports: ["6333:6333"]
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:0.3.14
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=/root/.ollama
      - OLLAMA_NO_GPU=1
    volumes:
      - ollama_models:/root/.ollama
      # mount your models (read-only is fine at runtime)
      - ./models:/models:ro
    ports: ["11434:11434"]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: local/rag-api:0.1.0
    restart: unless-stopped
    env_file: .env
    depends_on:
      qdrant: { condition: service_started }
      ollama: { condition: service_started }
    ports: ["8080:8000"]
    volumes:
      - ./data:/data

volumes:
  ollama_models:
  qdrant_storage:
